spring.application.name=sentrypay-backend


# 2. In-Memory H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:sentrypay_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sentry_user
spring.datasource.password=sentry_password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# 3. Change "update" to "create-drop" for H2 data seeding
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# 4. Optional: Enables the H2 web console so you can view your tables at localhost:8080/h2-console
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

# Make sure the H2 web console path is explicitly defined
spring.h2.console.path=/h2-console

# Fixes an H2 console UI rendering bug when using Spring Security (Frame Options)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


# declare the ActiveMQ broker URL, username, and password
# this is used to connect to the ActiveMQ message broker for sending and receiving messages
# in this case , we are using it to send transaction messages from springboot to cobol through activemq
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# add debug logging for Spring JMS to help troubleshoot message sending and receiving issues
logging.level.org.springframework.jms=DEBUG