INSERT INTO users (fullname, email, phone_number, dateof_birth, password, anti_phishing_name, created_at) VALUES ('Alice Smith', 'alice@sentrypay.com', '601234567', '1995-05-12', 'hashed_password_123', 'Shield-Sentry-2026', CURRENT_TIMESTAMP);
INSERT INTO users (fullname, email, phone_number, dateof_birth, password, anti_phishing_name, created_at) VALUES ('Bob Jones', 'bob@sentrypay.com', '601987654', '1990-11-23', 'hashed_password_456', 'Safe-Harbor-99', CURRENT_TIMESTAMP);
INSERT INTO users (fullname, email, phone_number, dateof_birth, password, anti_phishing_name, created_at) VALUES ('Charlie Brown', 'charlie@sentrypay.com', '601555555', '1988-04-02', 'hashed_password_789', 'Secure-Vault-88', CURRENT_TIMESTAMP);
INSERT INTO services (service_name, service_description, service_price, service_type, renewal_period , currency , services_id) VALUES ('Netflix Premium', 'Access to Netflix premium features and services.', 29.99, 'Banking', 'Monthly', 'USD', 'service_1');
INSERT INTO services (service_name, service_description, service_price, service_type, renewal_period, currency, services_id) VALUES ('Spotify Family', 'Access to Spotify family plan with multiple accounts.', 14.99, 'Banking', 'Monthly', 'USD', 'service_2');
INSERT INTO services (service_name, service_description, service_price, service_type, renewal_period, currency, services_id) VALUES ('Amazon Prime', 'Access to Amazon Prime benefits including free shipping and streaming.', 12.99, 'Banking', 'Monthly', 'USD', 'service_3');
INSERT INTO wallets (balance, currency, user_id , created_at) VALUES (100.00, 'USD', 1, CURRENT_TIMESTAMP);
INSERT INTO wallets (balance, currency, user_id, created_at) VALUES (50.00, 'USD', 2, CURRENT_TIMESTAMP);
INSERT INTO wallets (balance, currency, user_id, created_at) VALUES (75.00, 'USD', 3, CURRENT_TIMESTAMP);
INSERT INTO user_service_subscriptions (user_id, service_id, start_date, end_date, status) VALUES (1, 'service_1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'active');
INSERT INTO user_service_subscriptions (user_id, service_id, start_date, end_date, status) VALUES (1, 'service_2', CURRENT_TIMESTAMP, DATEADD('MONTH', 1, CURRENT_TIMESTAMP), 'active');
INSERT INTO user_service_subscriptions (user_id, service_id, start_date, end_date, status) VALUES (2, 'service_2', CURRENT_TIMESTAMP, DATEADD('MONTH', 1, CURRENT_TIMESTAMP), 'active');
INSERT INTO user_service_subscriptions (user_id, service_id, start_date, end_date, status) VALUES (3, 'service_3', CURRENT_TIMESTAMP, DATEADD('MONTH', 1, CURRENT_TIMESTAMP), 'active');
INSERT INTO user_transactions (sender_id, receiver_id, amount, created_at) VALUES (1, 2, 29.99, CURRENT_TIMESTAMP);
INSERT INTO user_transactions (sender_id, receiver_id, amount, created_at) VALUES (1, 3, 14.99, CURRENT_TIMESTAMP);
INSERT INTO user_transactions (sender_id, receiver_id, amount, created_at) VALUES (2, 1, 12.99, CURRENT_TIMESTAMP);
INSERT INTO user_transactions (sender_id, receiver_id, amount, created_at) VALUES (3, 1, 9.99, CURRENT_TIMESTAMP);
